version: '3'
services:
  db:
    image: mysql:5.6.34
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dev

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./app:/app:rw
    ports:
      - "3000:3000"
    depends_on:
      - db
